USE [master]
GO

/****** Object:  Database [SelfManagement.Tests]    Script Date: 08/03/2010 12:32:10 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'SelfManagement.Tests')
DROP DATABASE [SelfManagement.Tests]
GO

/****** Object:  Database [SelfManagement.Tests]    Script Date: 09/25/2010 14:59:43 ******/
CREATE DATABASE [SelfManagement.Tests]
GO

ALTER DATABASE [SelfManagement.Tests] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SelfManagement.Tests].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SelfManagement.Tests] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET ANSI_NULLS OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET ANSI_PADDING OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET ARITHABORT OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [SelfManagement.Tests] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [SelfManagement.Tests] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [SelfManagement.Tests] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET  DISABLE_BROKER
GO
ALTER DATABASE [SelfManagement.Tests] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [SelfManagement.Tests] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [SelfManagement.Tests] SET  READ_WRITE
GO
ALTER DATABASE [SelfManagement.Tests] SET RECOVERY SIMPLE
GO
ALTER DATABASE [SelfManagement.Tests] SET  MULTI_USER
GO
ALTER DATABASE [SelfManagement.Tests] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [SelfManagement.Tests] SET DB_CHAINING OFF
GO