USE [master]
GO

/****** Object:  Database [SelfManagement]    Script Date: 08/03/2010 12:32:10 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'SelfManagement')
DROP DATABASE [SelfManagement]
GO

/****** Object:  Database [SelfManagement]    Script Date: 09/25/2010 14:59:43 ******/
CREATE DATABASE [SelfManagement]
GO

ALTER DATABASE [SelfManagement] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SelfManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SelfManagement] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [SelfManagement] SET ANSI_NULLS OFF
GO
ALTER DATABASE [SelfManagement] SET ANSI_PADDING OFF
GO
ALTER DATABASE [SelfManagement] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [SelfManagement] SET ARITHABORT OFF
GO
ALTER DATABASE [SelfManagement] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [SelfManagement] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [SelfManagement] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [SelfManagement] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [SelfManagement] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [SelfManagement] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [SelfManagement] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [SelfManagement] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [SelfManagement] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [SelfManagement] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [SelfManagement] SET  DISABLE_BROKER
GO
ALTER DATABASE [SelfManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [SelfManagement] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [SelfManagement] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [SelfManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [SelfManagement] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [SelfManagement] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [SelfManagement] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [SelfManagement] SET  READ_WRITE
GO
ALTER DATABASE [SelfManagement] SET RECOVERY SIMPLE
GO
ALTER DATABASE [SelfManagement] SET  MULTI_USER
GO
ALTER DATABASE [SelfManagement] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [SelfManagement] SET DB_CHAINING OFF
GO